language: julia
os:
    # Temporarily commenting out osx because of Homebrew installation issue
    # of gcc 8.x. This causes the HDF5 build to attempt to build it from scratch
    # by downloading all of xcode which Travis CI then kills because it takes too long.
    # Refer to Matt Bauman's comment on JuliaIO/HDF5.jl issue 483, and
    # Andreas Noack's issue 27751 on Homebrew/homebrew-core.
    #- osx
    - linux
julia:
    - 0.7.0
notifications:
    email: false
addons:
  apt:
    packages:
    - hdf5-tools
    - libnlopt0
branches:
  only:
    - master
after_success:
- julia -e 'cd(Pkg.dir("ModelConstructors")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
